export default{
  SET_ALBUMS: "SET_ALBUMS",
  SET_ALBUMS_INFO: "SET_ALBUMS_INFO",
  SELECT_SONG: "SELECT_SONG",
  TOGGLE_PLAY: "TOGGLE_PLAY",
  LIKE_SONG: "LIKE_SONG",
  FETCH_ARTIST: "FETCH_ARTIST",
 
}

