export default{
    CREATE_LIST = "CREATE_LIST",
    DELETE_LIST = "DELETE_LIST",
    UPDATE_LIST = "UPDATE_LIST",
    ADD_TO_LIST = "ADD_TO_LIST",
    REMOVE_FROM_LIST = "REMOVE_FROM_LIST",
    SONG_LIKE = "SONG_LIKE",
    SONG_DISLIKE = "SONG_DISLIKE",
    EMPTY_LIST = "EMPTY_LIST",
    IS_LOADING = "IS_LOADING",
    SET_ERROR = "SET_ERROR",
}

